# sudo ufw allow 7879
# use this one for movies in TMDB that are not tagged "adult" ; these dont show up in Whisparr
---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarrx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - $CONFIG_DIR/radarr:/config
      - $MEDIA_DIR:$MEDIA_DIR
    ports:
      - 7879:7878
    restart: unless-stopped
