# use this to search for movies and scenes ; uses IMDB "adult" "movie" for movies
# uses StashDB for scenes and performers
# https://hotio.dev/containers/whisparr/#__tabbed_1_2
# https://github.com/Whisparr/Whisparr
# https://wiki.servarr.com/whisparr/quick-start-guide
# https://wiki.servarr.com/whisparr/library
---
services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=EST
    volumes:
      - $CONFIG_DIR/whisparr:/config
      - $APP_DIR/whisparr:/data
      - /mnt/media:/mnt/media
